name: Call Hello World Matrix

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  hello_world:
    uses: kammerdiener/github-common-workflows-example/.github/workflows/hello-world-matrix.yml@main
