name: Call Hello World Matrix Params

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  hello_world:
    uses: user1/hello-world-workflows/.github/workflows/hello-world-matrix-params.yml@main
    with:
      greeting: "Hello from the another repo!"